name: Pruebas C++

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Actividad 7.1
        run: cmake -S actividad-07 -B actividad-07/build -DCMAKE_BUILD_TYPE=Release

      - name: Compilar Actividad 7.1
        run: cmake --build actividad-07/build --config Release --parallel 2

      - name: Ejecutar pruebas de Actividad 7.1
        run: ctest --test-dir actividad-07/build --output-on-failure
